-- Migration: 0003_market_data.sql
-- Purpose: Add market_metrics table for agentic updates and seed baseline data.
-- SQLite / D1 Compatible
-- 1. Market Metrics (For Agentic Updates)
CREATE TABLE IF NOT EXISTS market_metrics (
    id TEXT PRIMARY KEY,
    -- UUID generated by app or random blob
    sector_id TEXT REFERENCES sectors(id),
    country_code TEXT REFERENCES countries(code),
    -- Metric details
    year INTEGER NOT NULL,
    market_size_usd INTEGER,
    -- SQLite doesn't have BIGINT enforced, INTEGER handles up to 8 bytes
    growth_rate REAL,
    -- DECIMAL -> REAL
    investment_volume_usd INTEGER,
    regulatory_outlook TEXT,
    -- 'Positive', 'Neutral', 'Negative', 'Volatile'
    top_companies_json TEXT,
    -- JSONB -> TEXT
    -- Metadata for Agentic Updates
    last_updated_by TEXT DEFAULT 'system',
    -- 'agent', 'manual'
    source_urls TEXT,
    -- JSONB -> TEXT
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(sector_id, country_code, year)
);
-- 2. Seed Baseline Data (2024-2025)
-- We use INSERT OR IGNORE or ON CONFLICT to allow agents to overwrite later.
INSERT OR IGNORE INTO market_metrics (
        id,
        sector_id,
        year,
        market_size_usd,
        growth_rate,
        investment_volume_usd,
        regulatory_outlook,
        top_companies_json
    )
VALUES -- Technology (Pan-African Baseline)
    (
        'uuid-tech-24',
        'technology',
        2024,
        18000000000,
        12.5,
        4500000000,
        'Positive',
        '["Flutterwave", "Interswitch", "Fawry", "M-Pesa"]'
    ),
    (
        'uuid-tech-25',
        'technology',
        2025,
        20500000000,
        14.2,
        5200000000,
        'Positive',
        '["Flutterwave", "Interswitch", "M-Pesa", "Paystack"]'
    ),
    -- Agriculture
    (
        'uuid-agri-24',
        'agriculture',
        2024,
        300000000000,
        4.2,
        12000000000,
        'Neutral',
        '["OCP Group", "Kenya Tea Dev", "Dangote Sugar"]'
    ),
    (
        'uuid-agri-25',
        'agriculture',
        2025,
        315000000000,
        5.1,
        13500000000,
        'Positive',
        '["OCP Group", "Olam Agri", "Dangote Sugar"]'
    ),
    -- Finance
    (
        'uuid-fin-24',
        'finance',
        2024,
        150000000000,
        6.8,
        8000000000,
        'Volatile',
        '["Standard Bank", "Ecobank", "Access Bank"]'
    ),
    (
        'uuid-fin-25',
        'finance',
        2025,
        162000000000,
        7.5,
        9500000000,
        'Neutral',
        '["Standard Bank", "FirstRand", "Attijariwafa"]'
    ),
    -- Energy
    (
        'uuid-nrg-25',
        'energy',
        2025,
        110000000000,
        3.5,
        25000000000,
        'Volatile',
        '["Sonatrach", "NNPC", "Sasol"]'
    );
-- 3. Update Countries with 2024/2025 Estimates (Live Data Baseline)
-- Nigeria
UPDATE countries
SET gdp_usd = 477400000000,
    population = 223800000,
    investment_highlights = '["Fintech Hub of Africa", "Oil & Gas Privatization", "Young Workforce"]',
    description = 'Nigeria is the largest economy in Africa and a major hub for fintech and cultural exports.'
WHERE code = 'NG';
-- South Africa
UPDATE countries
SET gdp_usd = 380900000000,
    population = 60600000,
    investment_highlights = '["Advanced Financial Markets", "Renewable Energy Transition", "Mining & Minerals"]',
    description = 'South Africa boasts the most advanced infrastructure and financial markets on the continent.'
WHERE code = 'ZA';
-- Egypt
UPDATE countries
SET gdp_usd = 398000000000,
    population = 111000000,
    investment_highlights = '["Green Hydrogen", "Suez Canal Economic Zone", "Tourism Revival"]',
    description = 'Egypt connects Africa and the Middle East, offering massive scale in renewables and logistics.'
WHERE code = 'EG';
-- Kenya
UPDATE countries
SET gdp_usd = 113400000000,
    population = 56200000,
    investment_highlights = '["Silicon Savannah", "Geothermal Energy Leader", "Tourism Hub"]',
    description = 'Kenya is the economic anchor of East Africa, known for tech innovation and sustainable energy.'
WHERE code = 'KE';
-- Rwanda
UPDATE countries
SET gdp_usd = 14100000000,
    population = 14100000,
    investment_highlights = '["Kigali International Financial Centre", "Ease of Doing Business", "Eco-Tourism"]',
    description = 'Rwanda is positioning itself as the Singapore of Africa with high ease of doing business.'
WHERE code = 'RW';
-- Ghana
UPDATE countries
SET gdp_usd = 76000000000,
    population = 34100000,
    investment_highlights = '["AfCFTA Headquarters", "Cocoa Processing", "Gold Mining"]',
    description = 'Ghana hosts the AfCFTA secretariat and is a beacon of democratic stability in West Africa.'
WHERE code = 'GH';
-- Morocco
UPDATE countries
SET gdp_usd = 147000000000,
    population = 37800000,
    investment_highlights = '["Automotive Manufacturing", "Aerospace Hub", "Solar Energy"]',
    description = 'Morocco is a key manufacturing gateway to Europe with world-class logistics and ports.'
WHERE code = 'MA';