-- Migration: 0003_market_data.sql
-- Purpose: Add market_metrics table for agentic updates and seed baseline data.
-- SQLite / D1 Compatible
-- 1. Market Metrics (For Agentic Updates)
CREATE TABLE IF NOT EXISTS market_metrics (
    id TEXT PRIMARY KEY,
    -- UUID generated by app or random blob
    sector_id TEXT REFERENCES sectors(id),
    country_code TEXT REFERENCES countries(code),
    -- Metric details
    year INTEGER NOT NULL,
    market_size_usd INTEGER,
    -- SQLite doesn't have BIGINT enforced, INTEGER handles up to 8 bytes
    growth_rate REAL,
    -- DECIMAL -> REAL
    investment_volume_usd INTEGER,
    regulatory_outlook TEXT,
    -- 'Positive', 'Neutral', 'Negative', 'Volatile'
    top_companies_json TEXT,
    -- JSONB -> TEXT
    -- Metadata for Agentic Updates
    last_updated_by TEXT DEFAULT 'system',
    -- 'agent', 'manual'
    source_urls TEXT,
    -- JSONB -> TEXT
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(sector_id, country_code, year)
);
-- 2. Market metrics are intentionally NOT seeded. Baselines fabricated without
-- primary sources were removed during the data-integrity remediation; rows are
-- now inserted only by the optimizer worker when a source-linked evidence
-- record supports the figures (see populateMarketMetrics in
-- src/lib/optimizer/market-data.ts, which sets source_urls and
-- last_updated_by = 'source-linked-worker').
-- 3. Update Countries with 2024/2025 Estimates (Live Data Baseline)
-- Nigeria
UPDATE countries
SET gdp_usd = 477400000000,
    population = 223800000,
    investment_highlights = '["Fintech Hub of Africa", "Oil & Gas Privatization", "Young Workforce"]',
    description = 'Nigeria is the largest economy in Africa and a major hub for fintech and cultural exports.'
WHERE code = 'NG';
-- South Africa
UPDATE countries
SET gdp_usd = 380900000000,
    population = 60600000,
    investment_highlights = '["Advanced Financial Markets", "Renewable Energy Transition", "Mining & Minerals"]',
    description = 'South Africa boasts the most advanced infrastructure and financial markets on the continent.'
WHERE code = 'ZA';
-- Egypt
UPDATE countries
SET gdp_usd = 398000000000,
    population = 111000000,
    investment_highlights = '["Green Hydrogen", "Suez Canal Economic Zone", "Tourism Revival"]',
    description = 'Egypt connects Africa and the Middle East, offering massive scale in renewables and logistics.'
WHERE code = 'EG';
-- Kenya
UPDATE countries
SET gdp_usd = 113400000000,
    population = 56200000,
    investment_highlights = '["Silicon Savannah", "Geothermal Energy Leader", "Tourism Hub"]',
    description = 'Kenya is the economic anchor of East Africa, known for tech innovation and sustainable energy.'
WHERE code = 'KE';
-- Rwanda
UPDATE countries
SET gdp_usd = 14100000000,
    population = 14100000,
    investment_highlights = '["Kigali International Financial Centre", "Ease of Doing Business", "Eco-Tourism"]',
    description = 'Rwanda is positioning itself as the Singapore of Africa with high ease of doing business.'
WHERE code = 'RW';
-- Ghana
UPDATE countries
SET gdp_usd = 76000000000,
    population = 34100000,
    investment_highlights = '["AfCFTA Headquarters", "Cocoa Processing", "Gold Mining"]',
    description = 'Ghana hosts the AfCFTA secretariat and is a beacon of democratic stability in West Africa.'
WHERE code = 'GH';
-- Morocco
UPDATE countries
SET gdp_usd = 147000000000,
    population = 37800000,
    investment_highlights = '["Automotive Manufacturing", "Aerospace Hub", "Solar Energy"]',
    description = 'Morocco is a key manufacturing gateway to Europe with world-class logistics and ports.'
WHERE code = 'MA';