-- 0030: AllAfrica per-country feeds for under-covered nations.
-- Counters the Nigeria/South-Africa coverage skew by sourcing the most
-- neglected countries directly from a trusted pan-African aggregator.
-- New rows have NULL last_fetched_at, so ingestion (least-recently-fetched
-- first) picks them up on the next run; the generator fair-share guard then
-- prioritises these under-covered countries over saturated ones.

INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-bi','AllAfrica · Burundi','rss','https://allafrica.com/tools/headlines/rdf/burundi/headlines.rdf','BI',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-ga','AllAfrica · Gabon','rss','https://allafrica.com/tools/headlines/rdf/gabon/headlines.rdf','GA',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-km','AllAfrica · Comoros','rss','https://allafrica.com/tools/headlines/rdf/comoros/headlines.rdf','KM',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-td','AllAfrica · Chad','rss','https://allafrica.com/tools/headlines/rdf/chad/headlines.rdf','TD',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-er','AllAfrica · Eritrea','rss','https://allafrica.com/tools/headlines/rdf/eritrea/headlines.rdf','ER',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-ls','AllAfrica · Lesotho','rss','https://allafrica.com/tools/headlines/rdf/lesotho/headlines.rdf','LS',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-mr','AllAfrica · Mauritania','rss','https://allafrica.com/tools/headlines/rdf/mauritania/headlines.rdf','MR',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-dj','AllAfrica · Djibouti','rss','https://allafrica.com/tools/headlines/rdf/djibouti/headlines.rdf','DJ',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-cf','AllAfrica · Central African Republic','rss','https://allafrica.com/tools/headlines/rdf/centralafricanrepublic/headlines.rdf','CF',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-ss','AllAfrica · South Sudan','rss','https://allafrica.com/tools/headlines/rdf/southsudan/headlines.rdf','SS',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-sl','AllAfrica · Sierra Leone','rss','https://allafrica.com/tools/headlines/rdf/sierraleone/headlines.rdf','SL',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-cv','AllAfrica · Cape Verde','rss','https://allafrica.com/tools/headlines/rdf/capeverde/headlines.rdf','CV',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-st','AllAfrica · Sao Tome and Principe','rss','https://allafrica.com/tools/headlines/rdf/saotomeandprincipe/headlines.rdf','ST',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-sz','AllAfrica · Eswatini','rss','https://allafrica.com/tools/headlines/rdf/eswatini/headlines.rdf','SZ',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-gw','AllAfrica · Guinea-Bissau','rss','https://allafrica.com/tools/headlines/rdf/guineabissau/headlines.rdf','GW',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-gq','AllAfrica · Equatorial Guinea','rss','https://allafrica.com/tools/headlines/rdf/equatorialguinea/headlines.rdf','GQ',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-sc','AllAfrica · Seychelles','rss','https://allafrica.com/tools/headlines/rdf/seychelles/headlines.rdf','SC',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-gm','AllAfrica · Gambia','rss','https://allafrica.com/tools/headlines/rdf/gambia/headlines.rdf','GM',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-ne','AllAfrica · Niger','rss','https://allafrica.com/tools/headlines/rdf/niger/headlines.rdf','NE',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-ml','AllAfrica · Mali','rss','https://allafrica.com/tools/headlines/rdf/mali/headlines.rdf','ML',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-tg','AllAfrica · Togo','rss','https://allafrica.com/tools/headlines/rdf/togo/headlines.rdf','TG',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-bj','AllAfrica · Benin','rss','https://allafrica.com/tools/headlines/rdf/benin/headlines.rdf','BJ',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-gn','AllAfrica · Guinea','rss','https://allafrica.com/tools/headlines/rdf/guinea/headlines.rdf','GN',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-lr','AllAfrica · Liberia','rss','https://allafrica.com/tools/headlines/rdf/liberia/headlines.rdf','LR',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-mw','AllAfrica · Malawi','rss','https://allafrica.com/tools/headlines/rdf/malawi/headlines.rdf','MW',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-na','AllAfrica · Namibia','rss','https://allafrica.com/tools/headlines/rdf/namibia/headlines.rdf','NA',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-bw','AllAfrica · Botswana','rss','https://allafrica.com/tools/headlines/rdf/botswana/headlines.rdf','BW',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-mg','AllAfrica · Madagascar','rss','https://allafrica.com/tools/headlines/rdf/madagascar/headlines.rdf','MG',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-so','AllAfrica · Somalia','rss','https://allafrica.com/tools/headlines/rdf/somalia/headlines.rdf','SO',NULL,1,60);
INSERT OR IGNORE INTO sources (id,name,type,url,country_code,sector_id,is_active,fetch_interval_minutes) VALUES ('s-aa-mu','AllAfrica · Mauritius','rss','https://allafrica.com/tools/headlines/rdf/mauritius/headlines.rdf','MU',NULL,1,60);
