-- 0031: Broaden the events calendar to under-represented countries/regions.
-- All are real, recurring pan-African summits/festivals. Dates are set to the
-- next upcoming edition; the daily rollRecurringEvents cron keeps them current.
INSERT OR IGNORE INTO events (id, title, date_start, date_end, location, country_code, category, status, is_featured, is_vip, description, slug, created_at) VALUES
('ev-fespaco-2027', 'FESPACO 2027', '2027-02-27', '2027-03-06', 'Ouagadougou, Burkina Faso', 'BF', 'Tourism', 'upcoming', 0, 0, 'The Panafrican Film and Television Festival of Ouagadougou — the continent''s largest and most prestigious celebration of African cinema.', 'fespaco-2027', datetime('now')),
('ev-sanganai-2026', 'Sanganai/Hlanganani World Tourism Expo 2026', '2026-10-14', '2026-10-16', 'Bulawayo, Zimbabwe', 'ZW', 'Tourism', 'upcoming', 0, 0, 'Zimbabwe''s premier international travel and tourism trade fair, connecting African destinations with global buyers.', 'sanganai-2026', datetime('now')),
('ev-niec-2027', 'Namibia International Energy Conference 2027', '2027-04-21', '2027-04-23', 'Windhoek, Namibia', 'NA', 'Energy', 'upcoming', 0, 0, 'Southern Africa''s flagship oil, gas and renewable energy conference, spotlighting Namibia''s emerging offshore discoveries.', 'niec-2027', datetime('now')),
('ev-iatf-2027', 'Intra-African Trade Fair 2027', '2027-09-04', '2027-09-10', 'Algiers, Algeria', 'DZ', 'Trade', 'upcoming', 1, 0, 'The continent''s largest trade and investment fair, driving intra-African commerce under the AfCFTA.', 'iatf-2027', datetime('now')),
('ev-tif-2027', 'Tunisia Investment Forum 2027', '2027-06-16', '2027-06-17', 'Tunis, Tunisia', 'TN', 'Investment', 'upcoming', 0, 0, 'Tunisia''s flagship gathering for international investors, entrepreneurs and policymakers across the Maghreb.', 'tif-2027', datetime('now')),
('ev-uma-tradefair-2026', 'UMA International Trade Fair 2026', '2026-10-05', '2026-10-14', 'Kampala, Uganda', 'UG', 'Trade', 'upcoming', 0, 0, 'East Africa''s largest manufacturing and trade exhibition, hosted by the Uganda Manufacturers Association.', 'uma-trade-fair-2026', datetime('now')),
('ev-brsc-2027', 'Botswana Resource Sector Conference 2027', '2027-05-04', '2027-05-06', 'Gaborone, Botswana', 'BW', 'Mining', 'upcoming', 0, 0, 'Botswana''s premier mining and natural-resources investment forum, from diamonds to critical minerals.', 'brsc-2027', datetime('now')),
('ev-promote-2027', 'PROMOTE 2027 - Yaoundé Trade Fair', '2027-02-20', '2027-02-28', 'Yaoundé, Cameroon', 'CM', 'Trade', 'upcoming', 0, 0, 'Central Africa''s largest enterprise and trade exhibition, showcasing business across the CEMAC region.', 'promote-2027', datetime('now')),
('ev-bamako-2026', 'Bamako Encounters - African Biennale of Photography 2026', '2026-11-07', '2026-12-07', 'Bamako, Mali', 'ML', 'Tourism', 'upcoming', 0, 0, 'The leading pan-African biennale of photography, drawing artists and curators from across the continent to Bamako.', 'bamako-encounters-2026', datetime('now')),
('ev-festival-kreol-2026', 'Festival Kreol 2026', '2026-10-23', '2026-10-31', 'Victoria, Seychelles', 'SC', 'Tourism', 'upcoming', 0, 0, 'Seychelles'' vibrant celebration of Creole heritage — music, cuisine, art and language across the islands.', 'festival-kreol-2026', datetime('now'));
