-- 0032: Extend the events calendar toward all-54 coverage.
-- Real, recurring events (mostly iconic festivals + established forums) for 20
-- more countries. Dates are the next upcoming edition; the daily
-- rollRecurringEvents cron keeps them current. Deliberately omits a handful of
-- conflict-affected / very small states (Sudan, CAR, Liberia, Comoros,
-- Djibouti, Gabon, Equatorial Guinea, São Tomé) rather than invent events.
INSERT OR IGNORE INTO events (id, title, date_start, date_end, location, country_code, category, status, is_featured, is_vip, description, slug, created_at) VALUES
('ev-libya-energy-2027', 'Libya Energy & Economic Summit 2027', '2027-01-18', '2027-01-19', 'Tripoli, Libya', 'LY', 'Energy', 'upcoming', 0, 0, 'North Africa''s summit on Libya''s oil, gas and post-conflict reconstruction economy.', 'libya-energy-summit-2027', datetime('now')),
('ev-vodun-days-2027', 'Vodun Days 2027', '2027-01-09', '2027-01-10', 'Ouidah, Benin', 'BJ', 'Tourism', 'upcoming', 0, 0, 'Benin''s government-backed celebration of Vodun heritage — music, ritual and diaspora tourism on the historic coast.', 'vodun-days-2027', datetime('now')),
('ev-ame-2027', 'Atlantic Music Expo 2027', '2027-04-07', '2027-04-10', 'Praia, Cape Verde', 'CV', 'Tourism', 'upcoming', 0, 0, 'A pan-Atlantic music market and showcase spotlighting African and diaspora artists from the Cabo Verde islands.', 'atlantic-music-expo-2027', datetime('now')),
('ev-roots-2027', 'Roots Homecoming Festival 2027', '2027-05-10', '2027-05-16', 'Banjul, Gambia', 'GM', 'Tourism', 'upcoming', 0, 0, 'The Gambia''s biennial diaspora heritage festival tracing the roots of the transatlantic story.', 'roots-festival-2027', datetime('now')),
('ev-guinea-mining-2026', 'Guinea Mining Symposium 2026', '2026-11-17', '2026-11-19', 'Conakry, Guinea', 'GN', 'Mining', 'upcoming', 0, 0, 'Guinea''s flagship bauxite, iron ore and critical-minerals investment symposium.', 'guinea-mining-symposium-2026', datetime('now')),
('ev-bissau-carnival-2027', 'Carnival of Bissau 2027', '2027-02-15', '2027-02-17', 'Bissau, Guinea-Bissau', 'GW', 'Tourism', 'upcoming', 0, 0, 'Guinea-Bissau''s vivid national carnival — masks, drumming and Bijagós traditions filling the capital.', 'bissau-carnival-2027', datetime('now')),
('ev-mauritanides-2026', 'Mauritanides 2026', '2026-11-24', '2026-11-26', 'Nouakchott, Mauritania', 'MR', 'Mining', 'upcoming', 0, 0, 'Mauritania''s premier mining, energy and petroleum conference and exhibition.', 'mauritanides-2026', datetime('now')),
('ev-cure-salee-2026', 'Cure Salée 2026', '2026-09-18', '2026-09-20', 'In-Gall, Niger', 'NE', 'Tourism', 'upcoming', 0, 0, 'Niger''s celebrated Tuareg and Wodaabe nomad gathering marking the end of the rainy season.', 'cure-salee-2026', datetime('now')),
('ev-freetown-music-2026', 'Freetown Music Festival 2026', '2026-12-27', '2026-12-28', 'Freetown, Sierra Leone', 'SL', 'Tourism', 'upcoming', 0, 0, 'Sierra Leone''s biggest live-music celebration, drawing West African and diaspora acts to the coast.', 'freetown-music-festival-2026', datetime('now')),
('ev-lome-forum-2026', 'Forum de Lomé 2026', '2026-12-03', '2026-12-04', 'Lomé, Togo', 'TG', 'Business', 'upcoming', 0, 0, 'Togo''s international forum on peace, security and sustainable development in Africa.', 'forum-de-lome-2026', datetime('now')),
('ev-burundi-fair-2026', 'Burundi International Trade Fair 2026', '2026-08-01', '2026-08-16', 'Bujumbura, Burundi', 'BI', 'Trade', 'upcoming', 0, 0, 'Burundi''s flagship trade exhibition connecting East African and Great Lakes businesses.', 'burundi-trade-fair-2026', datetime('now')),
('ev-eritrea-festival-2026', 'Festival Eritrea 2026', '2026-08-08', '2026-08-16', 'Asmara, Eritrea', 'ER', 'Tourism', 'upcoming', 0, 0, 'Eritrea''s national festival of music, craft and culture, held annually at the Asmara Expo grounds.', 'festival-eritrea-2026', datetime('now')),
('ev-madagascar-itm-2027', 'International Tourism Fair of Madagascar 2027', '2027-06-03', '2027-06-06', 'Antananarivo, Madagascar', 'MG', 'Tourism', 'upcoming', 0, 0, 'Madagascar''s premier tourism trade fair (ITM), showcasing the island''s biodiversity and hospitality.', 'madagascar-itm-2027', datetime('now')),
('ev-mogadishu-book-fair-2026', 'Mogadishu International Book Fair 2026', '2026-09-19', '2026-09-21', 'Mogadishu, Somalia', 'SO', 'Tourism', 'upcoming', 0, 0, 'Somalia''s landmark cultural gathering celebrating literature, ideas and the country''s creative revival.', 'mogadishu-book-fair-2026', datetime('now')),
('ev-ss-oil-power-2026', 'South Sudan Oil & Power 2026', '2026-11-10', '2026-11-11', 'Juba, South Sudan', 'SS', 'Energy', 'upcoming', 0, 0, 'South Sudan''s official oil, gas and power conference on the country''s energy future.', 'south-sudan-oil-power-2026', datetime('now')),
('ev-ndjamena-fair-2026', 'N''Djamena International Fair 2026', '2026-12-01', '2026-12-15', 'N''Djamena, Chad', 'TD', 'Trade', 'upcoming', 0, 0, 'Chad''s international trade fair (FIN), a marketplace for Sahel and Central African commerce.', 'ndjamena-fair-2026', datetime('now')),
('ev-fespam-2027', 'FESPAM 2027 - Pan-African Music Festival', '2027-07-17', '2027-07-24', 'Brazzaville, Republic of the Congo', 'CG', 'Tourism', 'upcoming', 0, 0, 'The Pan-African Music Festival, a UNESCO-recognised celebration of the continent''s musical heritage.', 'fespam-2027', datetime('now')),
('ev-bushfire-2027', 'MTN Bushfire 2027', '2027-05-28', '2027-05-30', 'Malkerns, Eswatini', 'SZ', 'Tourism', 'upcoming', 0, 0, 'Eswatini''s internationally acclaimed music and arts festival, one of Africa''s most celebrated.', 'bushfire-2027', datetime('now')),
('ev-morija-2026', 'Morija Arts & Cultural Festival 2026', '2026-10-02', '2026-10-05', 'Morija, Lesotho', 'LS', 'Tourism', 'upcoming', 0, 0, 'Lesotho''s leading celebration of Basotho heritage, music and mountain culture.', 'morija-festival-2026', datetime('now')),
('ev-lake-of-stars-2026', 'Lake of Stars 2026', '2026-09-25', '2026-09-27', 'Mangochi, Malawi', 'MW', 'Tourism', 'upcoming', 0, 0, 'Malawi''s renowned lakeside music festival on the shores of Lake Malawi, drawing global audiences.', 'lake-of-stars-2026', datetime('now'));
