-- 0033: Final verified events (researched) — brings the calendar to 52/54.
-- Sudan and CAR are deliberately omitted: they have no in-country recurring
-- major event (conflict-affected). Kept current by the daily roll cron.
INSERT OR IGNORE INTO events (id, title, date_start, date_end, location, country_code, category, status, is_featured, is_vip, description, slug, created_at) VALUES
('ev-libreville-forum-2027', 'Forum International de Libreville 2027', '2027-05-03', '2027-05-03', 'Libreville, Gabon', 'GA', 'Investment', 'upcoming', 0, 0, 'Gabon''s international forum on innovation and development, convening heads of state, investors and institutions at the Cité de la Démocratie.', 'forum-libreville-2027', datetime('now')),
('ev-djibouti-forum-2027', 'Djibouti Forum 2027', '2027-02-09', '2027-02-11', 'Djibouti City, Djibouti', 'DJ', 'Investment', 'upcoming', 0, 0, 'Djibouti''s flagship investment forum, convened by its Sovereign Wealth Fund to spotlight ports, logistics and emerging-market opportunity.', 'djibouti-forum-2027', datetime('now')),
('ev-limec-2026', 'LIMEC 2026 - Liberia International Mining & Energy Conference', '2026-10-28', '2026-10-29', 'Monrovia, Liberia', 'LR', 'Mining', 'upcoming', 0, 0, 'Liberia''s first international mining and energy conference, spotlighting iron ore, critical minerals and a US$3bn investment wave.', 'limec-2026', datetime('now')),
('ev-malabo-oilgas-2027', 'Oil & Gas Meeting Day Malabo 2027', '2027-05-19', '2027-05-20', 'Malabo, Equatorial Guinea', 'GQ', 'Energy', 'upcoming', 0, 0, 'Equatorial Guinea''s annual petroleum gathering in Malabo — licensing rounds, gas monetisation and upstream investment.', 'malabo-oil-gas-2027', datetime('now')),
('ev-ioi-forum-2027', 'Indian Ocean Islands Economic Forum 2027', '2027-04-26', '2027-04-28', 'Moroni, Comoros', 'KM', 'Investment', 'upcoming', 0, 0, 'The Indian Ocean islands'' economic forum, bringing regional business and investment leaders together to strengthen cross-island trade.', 'ioi-economic-forum-2027', datetime('now')),
('ev-stp-2040-2027', 'Sao Tome & Principe 2040 Investment Forum 2027', '2027-06-15', '2027-06-16', 'Sao Tome, Sao Tome and Principe', 'ST', 'Investment', 'upcoming', 0, 0, 'Sao Tome and Principe''s investment forum mobilising partners behind its 2040 national sustainable-development strategy.', 'stp-2040-forum-2027', datetime('now'));
